---
- name: Install kubectl
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: "0755"

- name: Install kind
  ansible.builtin.get_url:
    url: "https://kind.sigs.k8s.io/dl/{{ kind_version }}/kind-linux-amd64"
    dest: /usr/local/bin/kind
    mode: "0755"

- name: Download Helm archive
  ansible.builtin.unarchive:
    src: "https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz"
    dest: /tmp
    remote_src: true
    creates: /tmp/linux-amd64/helm

- name: Install Helm
  ansible.builtin.copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin/helm
    mode: "0755"
    remote_src: true
