name: devops-platform

services:
  webapp:
    build: ./app
    image: devops-platform/webapp:local
    container_name: webapp
    environment:
      APP_ENV: ${APP_ENV:-local}
      APP_VERSION: ${APP_VERSION:-0.1.0}
    ports:
      - "8080:8080"
    labels:
      logging: promtail
    restart: unless-stopped

  loadgen:
    image: curlimages/curl:8.9.1
    container_name: loadgen
    depends_on: [webapp]
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        while true; do
          curl -s http://webapp:8080/ > /dev/null
          curl -s http://webapp:8080/work > /dev/null
          sleep 1
        done

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./observability/prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:3.1.1
    container_name: loki
    command: -config.file=/etc/loki/loki.yml
    volumes:
      - ./observability/loki/loki.yml:/etc/loki/loki.yml:ro
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:3.1.1
    container_name: promtail
    command: -config.file=/etc/promtail/promtail.yml
    volumes:
      - ./observability/promtail/promtail.yml:/etc/promtail/promtail.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on: [loki]

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./observability/grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3000:3000"
    depends_on: [prometheus, loki]
