apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devops-platform
  namespace: argocd
spec:
  description: DevOps platform demo project
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
